-- ─────────────────────────────────────────────────────────────────────────────
-- Trip-details colophon.
--
-- Closing-page section that appears after the photo entries: a pull quote,
-- 5–7 label/value detail pairs, and a closing line. Generated by AI once
-- per journal (a second AI call after the narrative loop finishes) and then
-- editable by the user.
--
-- Stored as a single JSONB column to keep the migration small and to leave
-- room for the schema to evolve (item drag-reorder ordering, new sync
-- target types) without further DDL.
--
-- Default is { enabled: true } so journals created before this migration
-- show the colophon as soon as the user generates content for them.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.journals
  add column if not exists colophon jsonb;

comment on column public.journals.colophon is
  'Trip-details colophon. Shape: { enabled, pullQuote, closingLine, items: [{ id, label, value, visible, order, syncTo? }] }. Null until first generated.';
